apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jelease.fullname" . }}-relay-config
  labels:
    {{- include "jelease.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.relay.config | nindent 2 }}
