# SPDX-FileCopyrightText: 2024 Risk.Ident GmbH <contact@riskident.com>
#
# SPDX-License-Identifier: CC0-1.0

name: templ

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  templ:
    runs-on: ubuntu-latest
    name: Run templ generate
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install templ
        run: |
          TEMPL_VERISON=$(grep --perl-regexp --only-matching --max-count 1 'github.com/a-h/templ\s*\K(v.*)' go.mod)
          set -x
          go install github.com/a-h/templ/cmd/templ@$TEMPL_VERSION

      - name: Run templ
        run: templ generate

      - name: Fail on git diff
        run: git diff --exit-code
