# SPDX-FileCopyrightText: 2024 Risk.Ident GmbH <contact@riskident.com>
#
# SPDX-License-Identifier: CC0-1.0

name: templ

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  templ:
    runs-on: ubuntu-latest
    name: Run templ generate
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Run templ generate
        run: make generate

      - name: Fail on git diff
        run: git diff --exit-code
