on: [push]

jobs:
  govulncheck_job:
    runs-on: ubuntu-latest
    name: Run govulncheck
    steps:
      - uses: actions/checkout@v3

      - name: Get Go version
        id: goversion
        run: echo "version=$(grep '^go ' go.mod | grep --only-matching '[0-9.]*')" >> $GITHUB_OUTPUT

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: ">=${{ steps.goversion.outputs.version }}.0"
           go-package: ./...
